### ISSUE TITLE
ClamAV detected a trojan in code snippets

### ISSUE THREAD

**Issue by VoodooHillbilly** [PietJankbal/Chocolatey-for-wine#12]
Running clamscan on v0.5a.715 and a previous version detects this:
Chocolatey-for-wine/EXTRAS/powershell_collected_codesnippets_examples.ps1: Win.Trojan.PSempireInj-7013548-0 FOUND

**Comment by PietJankbal** [comment]
Hi thanks  for the report.
 I guess its because of the Invoke-ReflectivePEInjection example. You can check yourself that it's really harmless ( copy the base64 string into a file a.txt and do "cat a.txt | base64 -d >a.zip" and unzip that file). Any suggestions what todo? (I could of course remove it but maybe you have another idea)

**Comment by PietJankbal** [comment]
Hi, I removed the script from the release and offered it now as a download in winetricks.ps1 with a warning that it might trigger a virus warning. I think this should resolve this isssue. If you still encounter this viruswarning with latest release , please feel free to reopen this bugreport

Regards
