### ISSUE TITLE
Any chocolatey package fails if the package parameters character count is too long

### ISSUE THREAD

**Issue by Schroedingers-Cat** [PietJankbal/Chocolatey-for-wine#13]
I'm experiencing a rather weird issue. It seems to be caused by the character count of the chocolatey package parameters being too long. I haven't been able to identify an exact amount that triggers the problem, but something around 92 chars was always enough to trigger the problem over here. I can reproduce this in a few steps:
1. Install chocolatey-for-wine v0.5a.715 as described (tested with wine v8.8, v8.0, v7.18 and v7.9 with TKG's FSYNC patches)
2. Wait for the the pwsh.exe to open, then run:
3. `choco install chromium --package-parameters "'/SomeFunnyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyySwitch'"`
4. Installation script will run until the end and then suddenly crash:
```
Unhandled exception: page fault on execute access to 0x00000000006c006c in 64-bit code (0x000000006c006c).
Register dump:
 rip:00000000006c006c rsp:000000000031fe40 rbp:0075006e00240020 eflags:00010202 (  R- --  I   - - - )
 rax:0000000000000000 rbx:0024002000730074 rcx:00000000003500d0 rdx:0000000000000000
 rsi:006c006c0075006e rdi:006f0070002d0020  r8:000000000030ea0c  r9:0000000000350000 r10:0000000000399a20
 r11:0000000000750000 r12:0075005200740073 r13:006f006f0048006e r14:007200630053006b r15:0073007400700069
Stack dump:
0x0000000031fe40:  0000000000000000 000000000031fe90
0x0000000031fe50:  0000000000000000 0000000000000000
0x0000000031fe60:  0000000000000000 000000017005f3e8
0x0000000031fe70:  0000000000000000 00007e1100000000
0x0000000031fe80:  0000000000367610 0000000000000000
0x0000000031fe90:  0000000140008c60 0000000067ff0000
0x0000000031fea0:  ffffffffffffffff 000000017006e120
0x0000000031feb0:  0000000170026060 0000000000000000
0x0000000031fec0:  000000000031fea0 0000000000000000
0x0000000031fed0:  000000000031fe70 0000000000000000
0x0000000031fee0:  0000000000000000 0000000000000000
0x0000000031fef0:  0000000000000000 0000000000000000
Backtrace:
=>0 0x000000006c006c (0x75006e00240020)
0x000000006c006c: add %al, (%rax)
...
```

The switch in the example is meaningless and only there to get the point across. I'm actually having these crashes with private packages and package parameters like:
```
 --package-parameters "'/NoAaxx64 /NoAaxx86 /NoVst2x86 /NoVst2x64 /NoVst3x86 /NoUserFolder'"
```

While deleting any of the switches or even a single character from the switches fixes the issue (but it means that the switch won't be effective):
```
 --package-parameters "'/NoAaxx64 /NoAaxx86 /NoVst2x86 /NoVst2x64 /NoVst3x86'"
```

It should be noted that the script itself won't crash at a specific step. The chocolatey installation seems to crash the moment the package's installation script finishes, instead.

**Comment by PietJankbal** [comment]
Hi, thanks for the bugreport.

It looks like it's due to this line in mainv1.c (line 86):

...  cmdlineW[MAX_PATH]......

where MAX_PATH is  256. So it should be increased to something like 4096. I've changed it in the source and will include in future release (bit busy  now)

Meanwhile you could compile 64 and 32 bit powershell yourself with the fix like described in mainv1.c:

 x86_64-w64-mingw32-gcc -O1 -fno-ident -fno-stack-protector -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -falign-functions=1 -falign-jumps=1 -falign-loops=1 -fwhole-program\
 -mconsole -municode -mno-stack-arg-probe -Xlinker --stack=0x200000,0x200000 -nostdlib  -Wall -Wextra -ffreestanding  mainv1.c -lurlmon -lkernel32 -lucrtbase -luser32 -nostdlib -lshell32 -lntdll -s -o powershell.exe

(put it in c:\windows\system32\WindowsPowershell\v1.0)

and 
i686-w64-mingw32-gcc -O1 -fno-ident -fno-stack-protector -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -falign-functions=1 -falign-jumps=1 -falign-loops=1 -fwhole-program\
 -mconsole -municode -mno-stack-arg-probe -Xlinker --stack=0x200000,0x200000 -nostdlib  -Wall -Wextra -ffreestanding mainv1.c -lurlmon -lkernel32 -lucrtbase -luser32 -nostdlib -lshell32 -lntdll -s -o powershell.exe

(put it in c:\windows\syswow64\WindowsPowershell\v1.0)

**Comment by Schroedingers-Cat** [comment]
Thanks a lot, I can confirm that the fix is working!

**Comment by PietJankbal** [comment]
This is fixed now in most recent release
