### ISSUE TITLE
Upgrade to latest Powershell

### ISSUE THREAD

**Issue by natea11** [PietJankbal/Chocolatey-for-wine#16]
Hello,

I installed this repo and it worked fine but it said I needed to upgrade Powershell.

I ran:
wine choco upgrade powershell-core

Then I could not run wine anymore.

Is it possible to upgrade to the latest Powershell?

Thank you for the help.

**Comment by PietJankbal** [comment]
Hi,

Unfortunately PowerShell versions above 7.1.5. do not work in wine. It should however work when you use Wine-Staging; that has a patch for this wine-bug that works around the bug.

I pinned the version to 7.1.5 so that it should work both in wine and wine-staging, but maybe I can add a warning that one shouldn't upgrade poweshell-core. I'll have a look. 

Regards

**Comment by PietJankbal** [comment]
Hi,

In the next release (wine-8.19) the aforementioned wine-bug is fixed (fix went in two days ago), so with that version (comes out next week) you should also be able to upgrade to newer wine-versions (above 7.1.5). So for now I consider this as fixed

Regards

**Comment by natea11** [comment]
Thanks for your help.
